require("config.cmds")
require("core.lazy")
require("core.lsp")
require("config.options")
require("features.dotnet.startup")
-- vim.cmd("colorscheme cyberdream")
require("config.keymaps")
require("plugins.dap_utils.dotnet")
